### ISSUE TITLE
Unsafe link in readme

### ISSUE THREAD

**Issue by billfreeman44** [Bakkes/CPPRP#10]
Came across this repo today and wanted to mention the website RocketLeagueReplays.com has been taken over by some kind of bot/malware site. If it isn't important, I'd suggest removing the link.  I'm also happy to open a PR myself with a suggested fix if you'd like :)

**Comment by Bakkes** [comment]
I must've missed this issue. Looks like their domain has expired and is now used by spammers. I've updated the readme, thanks for letting me know!
