### ISSUE TITLE
Question about 'rotation' units

### ISSUE THREAD

**Issue by davechurchill** [Bakkes/CPPRP#16]
I am curious if you know exactly what units the 'rotation' data structure holds. For example, the z-axis 'rotation' appears to be:
- 0 when facing east
- 1 when facing west
- -0.7 when facing north
- +0.7 when facing south

I get the 0 / 1 for the east/west, buy why 0.7 for north/south? It's very close to sqrt(2)/2 but I can't decipher what's going on

**Comment by Bakkes** [comment]
Rotations should just be [quaternions](https://en.wikipedia.org/wiki/Quaternion). Rotations used to be simply euler angles but got changed to quaternions some time in [2018/2019](https://github.com/Bakkes/CPPRP/blob/master/CPPRP/NetworkDataParsers.h#L204)

**Comment by davechurchill** [comment]
Thank you!
